### ISSUE TITLE
А ти не думала/хочеш забрати той прямокутник зверху карточки противника і просто стиль міняти на той тригер або бекграунд?

### ISSUE THREAD

**Issue by ravenrebel** [ravenrebel/EpicRandomArena#5]
<StackPanel  Grid.Column="3" Grid.Row="0" VerticalAlignment="Center" HorizontalAlignment="Center">
            <Rectangle Width="144" Height="256">
                <Rectangle.Style>
                    <Style TargetType="Rectangle">
                        <Style.Triggers>
                            <DataTrigger Binding="{Binding Source={StaticResource viewmodel}, Path=IsYourTurn}" Value="true">
                                <Setter Property="Visibility" Value="Visible"></Setter>
                            </DataTrigger>
                            <DataTrigger Binding="{Binding Source={StaticResource viewmodel}, Path=IsYourTurn}" Value="false">
                                <Setter Property="Visibility" Value="Hidden"></Setter>
                            </DataTrigger>
                        </Style.Triggers>
                    </Style>
                </Rectangle.Style>
                <Rectangle.Fill>
                    <ImageBrush ImageSource="/EpicRandomArena;component/Graphics/BackCard.png"/>
                </Rectangle.Fill>
            </Rectangle>
        </StackPanel>

P.S. якщо забрати зайві штуки, буде швидше завантажуватись. @RudeBit4

**Comment by RudeBit4** [comment]
Відписала в лс в тг :3
